---

- name: Verify
  hosts: gpgkey
  tasks:

    - name: Fetch content of /proc/sys/kernel/random/entropy_avail
      slurp:
        src: /proc/sys/kernel/random/entropy_avail
      register: entropy
    - name: Validate entropy
      assert:
        that: >
          entropy['content'] | b64decode | int >= 300

    - name: Ensure /home/myuser/dupont.pub exists
      stat:
        path: /home/myuser/dupont.pub
      register: pub
    - name: Validate pub key present
      assert:
        that: pub.stat.exists and pub.stat.size != 0

    - name: Ensure /home/myuser/dupont.priv exists
      stat:
        path: /home/myuser/dupont.priv
      register: priv
    - name: Validate priv key present
      assert:
        that: priv.stat.exists and priv.stat.size != 0

    - name: Fetch content of /home/myuser/dupont.asc
      slurp:
        src: /home/myuser/dupont.asc
      register: asc
    - name: Validate asc export file
      assert:
        that: >
          "'-----BEGIN PGP PUBLIC KEY BLOCK-----' in asc['content'] | b64decode"
